controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

effort_controller:
  ros__parameters:
    joints:
      - linear_actuator_joint