bool startcmd
bool undocking
bool linear_dock
bool orientation_dock
float64 distance  
float64 orientation
string rack_no
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages
